
name: ASCII Workflow

on: 
 - push

jobs: 
    firstjob: 
         name: ASCII-Workflow
         runs-on: ubuntu-latest

         steps:
            - name: checkout 
              uses: actions/checkout@v4

            - name: permission on script
              run: chmod 400 ascii-script.sh  

            - name: execute ascii script
              run: ascii-script.sh
              





    