
name: ASCII Workflow

on: 
 - push

jobs: 
    firstjob: 
         name: ASCII-Workflow
         runs-on: ubuntu-latest

         steps:
            - name: checkout 
              uses: actions/checkout@v4

            - name: execcute ascii script
              run: ./ascii-script.sh
              





    